pipeline:
  build:
    image: ubuntu:xenial
    commands:
      - apt-get update
      - apt-get upgrade -qyy
      - apt-get -o APT::Install-Recommends=false -o APT::Install-Suggests=false install -y build-essential checkinstall zlib1g-dev libssl-dev libmysqlclient-dev libssl-dev libffi-dev libsqlite3-dev libxslt1-dev libjpeg-dev libbz2-dev libexpat1
      - ./configure
      - make -j4
      - checkinstall -D -y --pkggroup secdevops-vats --pkgname python --pkgversion 3.6 --pkgsource https://github.com/i4slabs/cpython/tree/3.6 --pkgaltsource https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz --maintainer I4S --nodoc --install=no --showinstall=no

  s3:
    image: plugins/s3
    acl: public-read
    region: eu-west-1
    bucket: tf-secdevops-drone
    source: /drone/src/github.com/i4slabs/python/build/python_3.6.0-1_amd64.deb
    target: /python/3.6.0/ubuntu/xenial/
    recursive: false
    strip_prefix: /drone/src/github.com/i4slabs/python/build/


    notify:
      image: plugins/slack
      channel: secdevops
      username: drone
      webhook: https://hooks.slack.com/services/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
